name: Lint
on:
    push:
    pull_request_target:
    workflow_dispatch:

permissions: write-all

jobs:
    format:
        name: Format
        runs-on: ubuntu-24.04
        concurrency: format-${{github.head_ref}}

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  token: ${{secrets.TOKEN || secrets.GITHUB_TOKEN}}
                  ref: ${{github.head_ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Setup Node.JS
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                  node-version-file: package.json
                  cache: npm

            - name: Install
              run: npm ci

            - name: Format
              run: node --run format

            - name: Assert clean
              if: startsWith(github.ref_name, 'dependabot/') == true
              run: if [[ `git status --porcelain` ]]; then exit 1; fi

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
              with:
                  commit_message: Format

    analyze:
        name: Analyze
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{github.head_ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Setup CodeQL
              uses: github/codeql-action/init@f09c1c0a94de965c15400f5634aa42fac8fb8f88 # v3.27.5
              with:
                  languages: javascript
                  queries: security-and-quality

            - name: Analyze
              uses: github/codeql-action/analyze@f09c1c0a94de965c15400f5634aa42fac8fb8f88 # v3.27.5

    build:
        name: Build
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{github.head_ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Setup Node.JS
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                  node-version-file: package.json
                  cache: npm

            - name: Install
              run: npm ci

            - name: Build
              run: node --run build

    test:
        name: Test
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{github.head_ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Setup Node.JS
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                  node-version-file: package.json
                  cache: npm

            - name: Install
              run: npm ci

            - name: Test
              run: node --run test
