name: Lint
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: 00 12 * * * # 1 hour before Dependabot

permissions: write-all

jobs:
    bump:
        name: Bump dependencies
        if: github.ref_name == 'main'
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
              with:
                  ref: ${{ github.head_ref }}

            - name: Bump
              id: sync_types
              uses: cobaltt7/sync-types@8136c927f35eaea3a14f3987132b14ae3366e2fe # v1.2.16

            - name: Commit
              id: commit
              uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
              with:
                  commit_message: Bump dependencies
                  branch: ${{ github.head_ref }}

            - name: Comment
              if: steps.commit.outputs.changes_detected == 'true'
              run: |
                  body="$(cat ${{ steps.sync_types.outputs.output-dir }}/changes.md)$(cat ${{ steps.sync_types.outputs.output-dir }}/sync.md)"
                  gh api "repos/${{ github.repository }}/commits/${{ steps.commit.outputs.commit_hash }}/comments" -F "body=$body"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    format:
        name: Format
        if: startsWith(github.ref_name, 'dependabot/') != true
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
              with:
                  node-version: "18.12.1"
                  cache: npm

            - name: Install
              run: npm ci

            - name: Format
              run: npm run format

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
              with:
                  commit_message: Format
                  branch: ${{ github.head_ref }}

    analyze:
        name: Analyze
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup CodeQL
              uses: github/codeql-action/init@29b1f65c5e92e24fe6b6647da1eaabe529cec70f # v2.3.3
              with:
                  languages: javascript
                  queries: security-and-quality

            - name: Analyze
              uses: github/codeql-action/analyze@e2b57b01d64b69ac273abfbea5d3ed15231e1706 # v2

    build:
        name: Build
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
              with:
                  node-version: "18.12.1"
                  cache: npm

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build
